# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-06-22 07:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restful01', '0002_auto_20180622_0712'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='usersinfo',
            name='role',
            field=models.ManyToManyField(default=1, to='restful01.Roles'),
        ),
    ]
